# Generated by Django 5.0.7 on 2024-07-21 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Code')),
                ('fine_gain', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fine Gain')),
                ('coarse_gain', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coarse Gain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Detector',
                'verbose_name_plural': 'Detectors',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Nuclide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('energy', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Energy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nuclide',
                'verbose_name_plural': 'Nuclides',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_detector', to='qa.detector')),
            ],
        ),
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roi_file', models.CharField(max_length=255, verbose_name='ROI File')),
                ('qa_prep', models.CharField(max_length=255, verbose_name='QA Prep')),
                ('lifetime', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lifetime')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='qa.session')),
            ],
            options={
                'verbose_name': 'Session Data',
                'verbose_name_plural': 'Session Data',
            },
        ),
        migrations.CreateModel(
            name='Spectrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centroid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Centroid')),
                ('net_count', models.PositiveBigIntegerField(verbose_name='Net Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spectrum', to='qa.sessiondata')),
            ],
            options={
                'verbose_name': 'Spectrum',
                'verbose_name_plural': 'Spectrums',
                'ordering': ['created_at'],
            },
        ),
    ]
