# Generated by Django 5.0.7 on 2024-07-25 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondata',
            name='detector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_detector', to='qa.detector'),
        ),
    ]
