# Generated by Django 5.0.7 on 2024-08-04 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuclide',
            name='halflife_time',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5, verbose_name='Halflife Time'),
        ),
        migrations.AddField(
            model_name='nuclide',
            name='halflife_time_units',
            field=models.CharField(choices=[('Sec', 'Seconds'), ('Min', 'Minutes'), ('Hour', 'Hours'), ('Day', 'Days'), ('Year', 'Years')], default='Year', max_length=10, verbose_name='Halflife Time Units'),
        ),
        migrations.AddField(
            model_name='roi',
            name='decay_corr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Decay Correction'),
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='is_reference',
            field=models.BooleanField(default=False, verbose_name='Is Reference'),
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='measurement_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Measurement Date'),
        ),
    ]
