# Generated by Django 5.0.7 on 2024-08-04 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_nuclide_halflife_time_nuclide_halflife_time_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondata',
            name='detector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_detector', to='qa.detector'),
        ),
    ]
