# Generated by Django 5.0.7 on 2024-08-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_alter_sessiondata_detector'),
    ]

    operations = [
        migrations.AddField(
            model_name='roi',
            name='fwhm',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='FWHM'),
        ),
        migrations.AddField(
            model_name='roi',
            name='pulsmax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Pulsmax Energy'),
        ),
    ]
