# Generated by Django 5.0.7 on 2024-08-10 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_roi_fwhm_roi_pulsmax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roi',
            name='decay_corr',
        ),
    ]
