# Generated by Django 5.0.7 on 2024-08-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_remove_roi_decay_corr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roi',
            name='centroid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Centroid'),
        ),
    ]
