# Generated by Django 5.0.7 on 2024-08-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_alter_roi_centroid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiondata',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approved session'),
        ),
    ]
